#encoding: utf-8

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: "Chicago" }, { name: "Copenhagen" }])
#   Mayor.create(name: "Emanuel", city: cities.first)

# for more: "http://www.businessinsider.com/the-best-thing-to-eat-in-every-country-2013-9?op=1"

Dish.delete_all

Dish.create(name: "Hamburger", country: "US", image_url: "http://olympiapizzaexpress.com/wp-content/themes/shopperpress/thumbs/hamburger-fast-food-french-fries-Favim.com-483020.jpg", description: "The U.S. is so vast and the cuisine so varied, it's nearly impossible to select just one dish to sum up American cuisine. But if you really twist our arm, we""d have to go with the all-American hamburger—especially when you pair it with crispy fries and a hearty milkshake.")
Dish.create(name: "Bulgogi", country: "Korea", image_url: "http://media.maangchi.com/wp-content/uploads/2008/03/bulgogi.jpg", description: "Beef bulgogi (fire meat) is a dish of thinly sliced, prime cuts of meat marinated in a mixture of soy sauce, sesame oil, garlic, onions, ginger, sugar, and wine and then grilled. It is often eaten wrapped in lettuce or spinach leaves and accompanied by kimchi (fermented vegetable pickle). Many Korean restaurants have miniature barbecues embedded in tables where diners grill the meat themselves.")
Dish.create(name: "Wiener Schnitzel", country: "Austria", image_url: "http://4.bp.blogspot.com/-fZZhsktSgYQ/UGbT__zH1nI/AAAAAAAAAhE/5p3PGSP5dnc/s1600/FB+SCHNITZEL+003+w+C.jpg", description: "Made with the finest ingredients and served fresh, this simple dish of pounded veal cutlets breaded and lightly fried is Austria’s food ambassador, despite the dish’s Italian origins. Austrians typically eat Wiener schnitzel garnished with parsley and lemon slices, a.")
Dish.create(name: "Feijoada", country: "Brazil", image_url: "http://mdemulher.abril.com.br/imagem/culinaria/galeria/receita-feijoada-frango.jpg", description: "Brazil is a huge country with varied cuisine so it's difficult to choose just one dish, but the most iconic Brazilian dish is probably feijoada, a stew of black beans and smoked beef and pork.")
Dish.create(name: "Tandoori Chicken", country: "India", image_url: "http://4.bp.blogspot.com/_5H-DnOEE9LQ/Sw33GJrg8lI/AAAAAAAAAcw/54cFqCQQYQ4/s1600/Tandoori+Chicken+Prep.JPG", description: "In India, the cuisine varies tremendously depending on the region, so it's nearly impossible to choose just one dish to sum up the country. In the north, dishes are more meat-heavy with rich curries and flavorful breads. The south has a lot more vegetarian dishes and is known for its intense spices.")
Dish.create(name: "Varenyky", country: "Ukraine", image_url: "http://pennappetit.com/wp-content/uploads/2013/10/Cherry-Varenyky.jpg", description: "Varenyky, or dumplings stuffed with mashed potatoes, cheese, sauerkraut, cabbage, or meat. They can be boiled or steamed, and typically come with toppings like fried salo (pig fat) and onions, along with smetana (sour cream).")
Dish.create(name: "Mole Sauce", country: "Mexico", image_url: "http://www.thebittenword.com/.a/6a00e55015ee528833017744caf99f970d-pi", description: "With up to 100 ingredients, mole sauce, is one of the most complex and flavorful sauces in the world, resulting in a rich, creamy, chocolatey and spicy flavor. It's originally from the Puebla and Oaxaca regions, but you can find mole sauce—usually doused over chicken or enchiladas—all over Mexico.")
Dish.create(name: "Poutine", country: "Canada", image_url: "http://4.bp.blogspot.com/_v45-TBo7M6U/TAg8cblcY9I/AAAAAAAAJr4/_VaVzH4Q6nI/s1600/Poutine+Fork.jpg", description: "Originally from Quebec, poutine is a delicious calorie-fest that will warm you from the insides: French fries topped with brown gravy and cheese curds. Quora user Josianne C. nominated this tasty dish.")
Dish.create(name: "Kabsah", country: "Saudi Arabia", image_url: "http://4.bp.blogspot.com/_9RhbJswSl7s/TSilPNlMMZI/AAAAAAAAAPk/BvxCMWoQo_I/s1600/IMGP0409.JPG", description: "Quora user Rafif F. suggested kabsah, a flavorful rice dish that's made with lots of spices, like cloves, cardamom, saffron, cinnamon, pepper, nutmeg, and bay leaves. It's usually mixed with meat and vegetables, making for a hearty meal.")
Dish.create(name: "Adobo", country: "Philippines", image_url: "http://crizzfood.com/wp-content/uploads/2013/12/adobo-yummy1.jpg", description: "Adobo may be a popular spice, but in the Philippines it's a dish that showcases some type of meat (pork or chicken) cooked in vinegar, soy sauce, garlic, and oil. It simmers in the marinade for a while, soaking up the flavors. The dish is so popular that some call it the unofficial national dish of the Philippines.")
